version: '3'
services:
  rentalservice:
    container_name: rental-service
    image: s1gawron/rental-service:1.1
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    depends_on:
      - database
      - rabbitmq
  database:
    container_name: mysql-rental
    image: mysql:8.0.26
    environment:
      MYSQL_DATABASE: rental_service
      MYSQL_USER: rentalServiceUser
      MYSQL_PASSWORD: changeit
      MYSQL_ROOT_PASSWORD: changeit
    ports:
      - "3306:3306"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"