POST {{host}}/api/tool/add
Content-Type: application/json
Authorization: Bearer

{
  "name": "Chainsaw",
  "description": "Ever wanted to cut trees?",
  "toolCategory": "LIGHT",
  "price": 150.99,
  "toolState": {
    "stateType": "WELL_WORN",
    "description": "Heavy used"
  },
  "imageUrl": "www.image.com/hammer"
}

###

PUT {{host}}/api/tool/edit
Content-Type: application/json
Authorization: Bearer

{
  "toolId": 1,
  "available": true,
  "name": "Chainsaw",
  "description": "Ever wanted to cut trees?",
  "toolCategory": "LIGHT",
  "price": 100.99,
  "toolState": {
    "stateType": "NEW",
    "description": "New and shiny tool"
  },
  "imageUrl": "www.image.com/chainsaw"
}

###

DELETE {{host}}/api/tool/delete/2
Authorization: Bearer
