POST {{host}}/api/public/user/register
Content-Type: application/json

{
  "email": "customer@test.pl",
  "password": "Start00!",
  "firstName": "John",
  "lastName": "Kowalski",
  "userRole": "CUSTOMER",
  "address": {
    "country": "Poland",
    "city": "Warsaw",
    "street": "Test",
    "postCode": "01-000"
  }
}

###

POST {{host}}/api/public/user/register
Content-Type: application/json

{
  "email": "worker@test.pl",
  "password": "Start00!",
  "firstName": "John",
  "lastName": "Koslak",
  "userRole": "WORKER"
}

###

POST {{host}}/api/public/user/login
Content-Type: application/json

{
  "email": "customer@test.pl",
  "password": "Start00!"
}

###

GET {{host}}/api/user/details
Content-Type: application/json
Authorization: Bearer

{
  "email": "worker@test.pl",
  "password": "Start00!"
}